name: flutter_template
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.2
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_translaty: ^1.0.7
  # Or use Standard Translation Tool Instead
  # flutter_localizations:
  #   sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^7.0.1
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  logging: ^1.1.1
  package_info_plus: ^4.0.1
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.17

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  golden_toolkit: ^0.15.0
  hive_generator: ^2.0.0
  mockito: ^5.3.2
  network_image_mock: ^2.1.1

flutter_native_splash:
  color: "#02A8AD"
  android: true
  ios: true

flutter:
  # only enable on standard translation
  # generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - translaty.yaml
    - assets/translations/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
